name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish-node-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Volta
        uses: volta-cli/action@v3
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Build and publish to NPM
        run: |
          yarn
          yarn run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Volta for Github Packages
        uses: volta-cli/action@v3
        with:
          registry-url: "https://npm.pkg.github.com"
        
      - name: Publish to Github Packages
        run: npm publish
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}